# Residency-1: Project-1 | Statistical Learning | Jayant Ojha

In [386]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [387]:
import pandas as pd
import numpy as np

## 1. Steps for Importing and Cleaning of data

In [388]:
#Store data from external csv to an initial datframe variable
df = pd.read_csv("./Laliga.csv")

In [389]:
#Get some basic info on shape and data types etc
df.shape
df.info()

(62, 20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 20 columns):
Unnamed: 0     62 non-null object
Unnamed: 1     62 non-null object
Unnamed: 2     62 non-null object
Unnamed: 3     62 non-null object
Unnamed: 4     62 non-null object
Unnamed: 5     62 non-null object
Unnamed: 6     62 non-null object
Unnamed: 7     62 non-null object
Unnamed: 8     62 non-null object
Unnamed: 9     62 non-null object
Unnamed: 10    62 non-null object
Unnamed: 11    62 non-null object
Unnamed: 12    62 non-null object
Unnamed: 13    62 non-null object
Unnamed: 14    62 non-null object
Unnamed: 15    62 non-null object
Unnamed: 16    62 non-null object
Unnamed: 17    62 non-null object
Unnamed: 18    62 non-null object
Unnamed: 19    62 non-null object
dtypes: object(20)
memory usage: 9.8+ KB

In [390]:
#Also explore column-labels, row-indices, and a few rows of data.
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1

In [391]:
#As the above shows, a presence of column-labels with names like "Unnamed:#" etc
#which isn't useful. While the row-index 0 shows the values, which sound more like
#column-labels. Hence the current column labels need to replaced, with the data from
#first-row data-values.Hence changing them by replacing with 0th row-index, as 
#given below
df.columns = df.iloc[0]
df.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1

In [392]:
#Above step leaves us with extra row values, for 0th index which doesn't make sense any longer
#hence the whole data needs to be reindexed to start from 1st row instead.Storing the reindexed
#dataframe to a new dataframe variable: "laliga", which we plan to use in the later steps.
laliga =df.reindex(df.index.drop(0))
laliga.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
1,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
2,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
3,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
4,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
5,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1

In [393]:
#The side effect of above is that we have a slightly "unconventional" datframe row-indices
#starting from 1st (instead of more traditional 0th start), hence reset-index is required
#with the extra intermediate "index" column dropped & saving it "inplace", in to the same
#variable, in single step: to "finally" get the data in the "desired usable format"!
laliga.reset_index(drop=True, inplace=True)
laliga.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
1,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
2,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
3,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1

### Q1. Read the data set and replace dashes with 0 to make sure, can perform arithmetic operations on the data

In [394]:
#Replace all hyphens with values 0, and save it "inplace"(onto the laliga dataframe)
laliga.replace('-', 0, inplace=True)
laliga.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
1,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
2,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
3,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1

### Q2. Print all the teams which have started playing between 1930-1980.

In [395]:
#Convert the Debut values to numeric-unsigned int type: 

#This requires us to first split years like 2002-03 etc. to be split at the hyphens, 
#and just the first part taken: i.e. 2002 for this given example.

#The second step is to convert the data-type to unsigned int, so that the series can be sorted
#on basis of the year etc.
laliga['Debut'] = pd.to_numeric(laliga['Debut'].map(lambda x:x.split('-', 1)[0]), downcast='unsigned')

In [396]:
#Observe few rows
laliga.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
1,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
2,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
3,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931,1987-88,1
4,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1

In [397]:
#Now the "Team" column can be filtered using the "Debut" as between
#year 1930-1980, as given below:
laliga.loc[(laliga.Debut >= 1930) & (laliga.Debut <= 1980), ["Team"]]

0                  Team
3              Valencia
5               Sevilla
8              Zaragoza
9            Real Betis
10  Deportivo La Coruna
11           Celta Vigo
12           Valladolid
14       Sporting Gijon
15              Osasuna
16               Malaga
17               Oviedo
18             Mallorca
19           Las Palmas
21              Granada
22       Rayo Vallecano
23                Elche
25             Hercules
26             Tenerife
27               Murcia
28               Alaves
29              Levante
30            Salamanca
31             Sabadell
32                Cadiz
34            Castellon
37              Cordoba
39           Recreativo
40            Burgos CF
41           Pontevedra
46            Gimnastic
49             Alcoyano
50                 Jaen
52           AD Almeria
54               Lleida
57               Condal
58      Atletico Tetuan
59     Cultural Leonesa

### Q3. Print the list of teams which came Top 5 in terms of points

In [398]:
#Again convert the dataframe-"Points" column series, to an unsigned int type
#so that it can be sorted in either ascending or descending order of Points
#gained
laliga['Points'] = pd.to_numeric(laliga['Points'], downcast='unsigned')

In [399]:
#Now sort the datframe by Points & store to a temp dataframe
#and display/print the 5 "Teams" thru the temp dataframe
#This ordering can be cross-validated thru the "Pos" column field
#as well.
teams_pointwise = laliga.sort_values(by=['Points'],ascending=False)
teams_pointwise.loc[:, ["Team"]].head(n=5)

0             Team
0      Real Madrid
1        Barcelona
2  Atletico Madrid
3         Valencia
4  Athletic Bilbao

### Q4. Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. Using the same function, find the team which has maximum and minimum goal difference. Where the definition for: Goal_diff_count = GoalsFor - GoalsAgainst

In [400]:
#Again, first convert the dataframe-"GoalsFor" column series, to an unsigned int type
laliga['GoalsFor'] = pd.to_numeric(laliga['GoalsFor'], downcast='unsigned')

In [401]:
#Next, convert the dataframe-"GoalsAgainst" column series, to an unsigned int type
laliga['GoalsAgainst'] = pd.to_numeric(laliga['GoalsAgainst'], downcast='unsigned')

In [402]:
#Define a func with name: “Goal_diff_count”, which returns the dataframe with an extra column
#named 'Goal_diff_count', which is a difference of passed dataframe columns 'GoalsFor' with
#'GoalsAgainst'.The given dataframe can "apply" this function to add  an extra column of "goal_diff_count"
#calculations.
def Goal_diff_count(df):
    df['Goal_diff_count'] = df['GoalsFor'] - df['GoalsAgainst']
    return (df)

In [403]:
#The following line "applies" the above function and has to save to the 
#same dataframe to save the extra column "inplace".
laliga = laliga.apply(Goal_diff_count, axis=1)

In [404]:
#observe the datframe to see the new column added(the "Goal_diff_count" one)
laliga.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,...,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition,Goal_diff_count
0,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,...,23,8,8,3,4,79,1929,1929,1,2807
1,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,...,25,12,12,4,6,83,1929,1929,1,2786
2,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,...,8,16,9,7,6,56,1929,2002-03,1,1225
3,4,Valencia,82,3386,2664,1187,616,861,4398,3469,...,6,10,11,10,7,50,1931,1987-88,1,929
4,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,...,7,10,5,8,10,49,1929,1929,1,931

In [405]:
#This modified dataframe's "Goal_diff_count"series, can be used to return the team with 
#max series value, as given below ((in this case a value: +2807))
laliga.loc[(laliga.Goal_diff_count == laliga.Goal_diff_count.max()), ["Team"]]

0         Team
0  Real Madrid

In [406]:
#Similarly, this modified dataframe's "Goal_diff_count"series can also be used, to return the team with 
#min series value, as given below (in this case a value: -525)
laliga.loc[(laliga.Goal_diff_count== laliga.Goal_diff_count.min()), ["Team"]]

0               Team
13  Racing Santander

### Q5. Create a new column with name “Winning Percent” and append it to the data set  Percentage of Winning = (GamesWon / GamesPlayed)*100. If there are any numerical error, replace it with 0%.Print the top 5 teams which has the highest Winning percentage

In [407]:
#Again, first convert the dataframe-"GamesWon" column series, to an unsigned int type
laliga['GamesWon'] = pd.to_numeric(laliga['GamesWon'], downcast='unsigned')

In [408]:
#Again, first convert the dataframe-"GamesPlayed" column series, to an unsigned int type
laliga['GamesPlayed'] = pd.to_numeric(laliga['GamesPlayed'], downcast='unsigned')

In [409]:
#Set the float-format to two places after decimals
#And add an extra coumn named: 'Winning_Percent' which has:
# the Percentage of Winning = (GamesWon / GamesPlayed)*100 only if GamesPlayed is not equal to 0
#otherwise a divison by zero error can occur.
pd.options.display.float_format = '{:,.2f}'.format
laliga['Winning_Percent'] = np.where((laliga['GamesPlayed'] != 0), (laliga['GamesWon']/laliga['GamesPlayed'])*100, 0)

In [410]:
#observe results
laliga.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,...,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition,Goal_diff_count,Winning_Percent
0,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,...,8,8,3,4,79,1929,1929,1,2807,59.63
1,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,...,12,12,4,6,83,1929,1929,1,2786,57.24
2,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,...,16,9,7,6,56,1929,2002-03,1,1225,47.48
3,4,Valencia,82,3386,2664,1187,616,861,4398,3469,...,10,11,10,7,50,1931,1987-88,1,929,44.56
4,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,...,10,5,8,10,49,1929,1929,1,931,43.77

In [411]:
#Now sort the datframe by Winning_Percent & store to a temp dataframe
#and display/print the 5 "Teams" thru this new temp dataframe
#This ordering can be cross-validated thru the "Pos" column field
#as well.
teams_win_percent = laliga.sort_values(by=['Winning_Percent'],ascending=False)
teams_win_percent.loc[:, ["Team"]].head(n=5)

0             Team
0      Real Madrid
1        Barcelona
2  Atletico Madrid
3         Valencia
4  Athletic Bilbao

### Q6. Group teams based on their “Best position” and print the sum of their points for all positions.
Eg:---Best Position--------------------- Points----

         1                   25000

         2                    7000

In [412]:
#Again, first convert the dataframe-"BestPosition" column series, to an unsigned int type
#The 'Points' column which needs to be summed up is already uint(due to earlier questions)
laliga['BestPosition'] = pd.to_numeric(laliga['BestPosition'], downcast='unsigned')

In [413]:
#Groupby the dataframe based on the “Best position” and use the 'points' column
#to apply the "sum" agg-func on the same.The new multi-level column label is 
#also replaced as required by the Q6.
tmp_best_pos = laliga.groupby('BestPosition').agg({'Points':['sum']})
tmp_best_pos.columns = [ 'Points']
tmp_best_pos.head()

              Points
BestPosition
1              27933
2               6904
3               5221
4               6563
5               1884

# End Of Assignment